// import './globals.css'
import '@/styles/globals.css'
import '../styles/Sass/global.css'
import Navbar from '@/components/nave-bar/Navbar'
import Footer from '@/components/footer/Footer'
import AuthProvider from '@/components/auth-provider/AuthProvider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AuthProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </AuthProvider>
        {/* <ToastContainer /> */}
      </body>
    </html>
  )
}
