// import './globals.css'
import '@/styles/globals.css'
import '../styles/Sass/global.css'
import Navbar from '@/components/nave-bar/Navbar'
import Footer from '@/components/footer/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
